# This is a basic workflow to help you get started with Actions

name: Glog scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  glog-scan:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, Learning Github Actions!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          rm $GITHUB_WORKSPACE/.glog/*
          /home/vjelic/Documents/Projects/glog-tools/glog.sh scan --path $GITHUB_WORKSPACE --lang java
